#Edward Yaroslavsky and Jared Follet
#I pledge my honor that I have abided by the Stevens Honor System.

CC = gcc
CFLAGS = -g -Wall -Werror -pedantic-errors
all:
	$(CC) $(CFLAGS) -o chatclient chatclient.c
	$(CC) $(CFLAGS) -o chatserver chatserver.c
clean:
	rm client server